name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the deployment on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment (if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Adjust to your Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build your static site (if using a build step like webpack)
      - name: Build static site
        run: npm run build  # Adjust if you have a different build command

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch where the built site will be pushed
          folder: build  # The folder containing your build output (adjust if needed)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub
